# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# 修正 grpcio-tools 生成的扁平导入，改为包内相对导入，
# 使其可作为 serving.proto.autovisionagent_pb2_grpc 正常导入。
from serving.proto import autovisionagent_pb2 as autovisionagent__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autovisionagent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutoVisionAgentServiceStub:
    """===========================================================================
    AutoVisionAgent 对外服务。
    设计：gRPC 作为控制信道（RPC 契约 + 小结果元数据），
    共享内存作为大块二进制数据的零拷贝通道。
    ===========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/Ping',
                request_serializer=autovisionagent__pb2.PingRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.PongResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/ListTasks',
                request_serializer=autovisionagent__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.GetTaskInfo = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/GetTaskInfo',
                request_serializer=autovisionagent__pb2.GetTaskInfoRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.TaskInfo.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/LoadModel',
                request_serializer=autovisionagent__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/UnloadModel',
                request_serializer=autovisionagent__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.Detect = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/Detect',
                request_serializer=autovisionagent__pb2.DetectRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.ReleaseSharedMemory = channel.unary_unary(
                '/autovisionagent.v1.AutoVisionAgentService/ReleaseSharedMemory',
                request_serializer=autovisionagent__pb2.ReleaseSharedMemoryRequest.SerializeToString,
                response_deserializer=autovisionagent__pb2.ReleaseSharedMemoryResponse.FromString,
                _registered_method=True)


class AutoVisionAgentServiceServicer:
    """===========================================================================
    AutoVisionAgent 对外服务。
    设计：gRPC 作为控制信道（RPC 契约 + 小结果元数据），
    共享内存作为大块二进制数据的零拷贝通道。
    ===========================================================================
    """

    def Ping(self, request, context):
        """健康检查。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """列出全部任务能力。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskInfo(self, request, context):
        """查询单个任务状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """加载有监督引擎权重。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """卸载引擎、释放显存。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """单图推理。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSharedMemory(self, request, context):
        """回收由本服务创建的共享内存文件。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoVisionAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=autovisionagent__pb2.PingRequest.FromString,
                    response_serializer=autovisionagent__pb2.PongResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=autovisionagent__pb2.ListTasksRequest.FromString,
                    response_serializer=autovisionagent__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetTaskInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskInfo,
                    request_deserializer=autovisionagent__pb2.GetTaskInfoRequest.FromString,
                    response_serializer=autovisionagent__pb2.TaskInfo.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=autovisionagent__pb2.LoadModelRequest.FromString,
                    response_serializer=autovisionagent__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=autovisionagent__pb2.UnloadModelRequest.FromString,
                    response_serializer=autovisionagent__pb2.UnloadModelResponse.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=autovisionagent__pb2.DetectRequest.FromString,
                    response_serializer=autovisionagent__pb2.DetectResponse.SerializeToString,
            ),
            'ReleaseSharedMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSharedMemory,
                    request_deserializer=autovisionagent__pb2.ReleaseSharedMemoryRequest.FromString,
                    response_serializer=autovisionagent__pb2.ReleaseSharedMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autovisionagent.v1.AutoVisionAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autovisionagent.v1.AutoVisionAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutoVisionAgentService:
    """===========================================================================
    AutoVisionAgent 对外服务。
    设计：gRPC 作为控制信道（RPC 契约 + 小结果元数据），
    共享内存作为大块二进制数据的零拷贝通道。
    ===========================================================================
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/Ping',
            autovisionagent__pb2.PingRequest.SerializeToString,
            autovisionagent__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/ListTasks',
            autovisionagent__pb2.ListTasksRequest.SerializeToString,
            autovisionagent__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/GetTaskInfo',
            autovisionagent__pb2.GetTaskInfoRequest.SerializeToString,
            autovisionagent__pb2.TaskInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/LoadModel',
            autovisionagent__pb2.LoadModelRequest.SerializeToString,
            autovisionagent__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/UnloadModel',
            autovisionagent__pb2.UnloadModelRequest.SerializeToString,
            autovisionagent__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/Detect',
            autovisionagent__pb2.DetectRequest.SerializeToString,
            autovisionagent__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSharedMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autovisionagent.v1.AutoVisionAgentService/ReleaseSharedMemory',
            autovisionagent__pb2.ReleaseSharedMemoryRequest.SerializeToString,
            autovisionagent__pb2.ReleaseSharedMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
